apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: digits-recognizer
  namespace: kubeflow-user-example-com
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  predictor:
    serviceAccountName: sa-minio-kserve
    tensorflow:
      storageUri: s3://mlpipeline/models/detect-digits/
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"